# Generated by Django 3.1.7 on 2021-04-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210406_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
