# Generated by Django 3.1.7 on 2021-04-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210406_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='count',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
