# Generated by Django 3.1.7 on 2021-04-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210406_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adress1',
            new_name='address1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='adress2',
            new_name='address2',
        ),
    ]
